package cli

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"strings"

	"birdcage/internal/wgkey"
)

// RunInit handles "birdcage init" — interactive server setup.
func RunInit() {
	if len(os.Args) > 1 && (os.Args[1] == "--help" || os.Args[1] == "-h") {
		fmt.Println("birdcage init — generate server configuration")
		fmt.Println()
		fmt.Println("Usage")
		fmt.Println("  birdcage init    Interactive setup — generates .env in the current directory")
		fmt.Println()
		fmt.Println("Generates JWT secrets, an agent key, and a WireGuard keypair.")
		fmt.Println("Writes a .env file you can review and edit.")
		fmt.Println("Does not start anything — you run 'birdcage serve' when ready.")
		return
	}

	if _, err := os.Stat(".env"); err == nil {
		fmt.Print(".env already exists. Overwrite? [y/N] ")
		reader := bufio.NewReader(os.Stdin)
		answer, _ := reader.ReadString('\n')
		if strings.TrimSpace(strings.ToLower(answer)) != "y" {
			fmt.Println("Aborted.")
			return
		}
	}

	reader := bufio.NewReader(os.Stdin)

	fmt.Print("Base URL [http://localhost:8080]: ")
	baseURL, _ := reader.ReadString('\n')
	baseURL = strings.TrimSpace(baseURL)
	if baseURL == "" {
		baseURL = "http://localhost:8080"
	}

	fmt.Print("WireGuard endpoint (this server's public IP:port, e.g. 203.0.113.1:51820) []: ")
	wgEndpoint, _ := reader.ReadString('\n')
	wgEndpoint = strings.TrimSpace(wgEndpoint)

	wgPort := "51820"
	if wgEndpoint != "" {
		if _, p, ok := strings.Cut(wgEndpoint, ":"); ok && p != "" {
			wgPort = p
		}
	}

	accessSecret := randomHex(32)
	refreshSecret := randomHex(32)
	agentKey := randomHex(32)
	registrationToken := randomHex(32)

	// Generate WireGuard keypair for the server
	wgPrivKey, wgPubKey, err := wgkey.GenerateKeypair()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating WireGuard keypair: %v\n", err)
		os.Exit(1)
	}

	content := fmt.Sprintf(`# birdcage server configuration
# Generated by: birdcage init
# Review and edit before running: birdcage serve

# --- Authentication ---
JWT_ACCESS_SECRET=%s
JWT_REFRESH_SECRET=%s

# --- Registration ---
# Required to register the owner account. Printed during init.
REGISTRATION_TOKEN=%s

# --- Agent ---
# Give this key to the home agent: birdcage agent init <server-url> <key>
AGENT_KEY=%s

# --- Server ---
BASE_URL=%s
DB_PATH=birdcage.db
# ADDR=:443  (derived from BASE_URL if omitted)

# --- TLS (automatic when BASE_URL uses https://) ---
# CERT_DIR=certs

# --- Control proxy (claw gateway) ---
# Set these after WireGuard is running. GATEWAY_URL uses the home machine's mesh IP.
# GATEWAY_URL=http://10.0.0.2:18789
# GATEWAY_TOKEN=

# --- WireGuard ---
WG_PRIVATE_KEY=%s
WG_LISTEN_PORT=%s
# Public IP:port where agents send WireGuard UDP traffic (this server's IP)
WG_ENDPOINT=%s
# WG_INTERFACE=wg0
`, accessSecret, refreshSecret, registrationToken, agentKey,
		baseURL,
		wgPrivKey, wgPort, wgEndpoint)

	if err := os.WriteFile(".env", []byte(content), 0600); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing .env: %v\n", err)
		os.Exit(1)
	}

	fmt.Println()
	fmt.Println("Created .env")
	fmt.Printf("  Base URL:   %s\n", baseURL)
	if strings.HasPrefix(baseURL, "https://") {
		fmt.Println("  TLS:        automatic (Let's Encrypt)")
	}
	fmt.Printf("  Reg token:  %s\n", registrationToken)
	fmt.Printf("  WG pubkey:  %s\n", wgPubKey)
	fmt.Printf("  Agent key:  %s\n", agentKey)
	fmt.Println()
	fmt.Println("Next steps")
	fmt.Println("  1. Review .env — set GATEWAY_URL after the agent connects")
	fmt.Println("  2. Start server:  sudo birdcage serve")
	fmt.Printf("  3. On home machine: birdcage agent init %s %s\n", baseURL, agentKey)
	fmt.Println("  4. Start agent:   sudo birdcage agent")
}

func randomHex(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		panic("crypto/rand: " + err.Error())
	}
	return hex.EncodeToString(b)
}
